export {
  buildPlacementVariants,
  canPieceUseInPlaceOrientation,
  canPiecesConnect,
  createId,
  createInitialStationLayout as createInitialEditorState,
  createPieceRecord,
  getAllConnectionEndpointKeysForPiece,
  getAllowedPlacements,
  getConnectionEndpointKey,
  getConnectionPieceId,
  getPieceCells,
  getRenderablePieces,
  isSwitchButtonPieceType,
  isSwitchPieceType,
  parseCellRef,
  toCellKey,
} from '@/lib/station/layout';
