export {
  buildPlacementVariants,
  canPieceUseInPlaceOrientation,
  canPiecesConnect,
  createId,
  createInitialStationLayout as createInitialEditorState,
  createPieceRecord,
  expandStationLayout,
  getAllConnectionEndpointKeysForPiece,
  getAllowedPlacements,
  getConnectedPieceIdsForEndpointKey,
  getConnectionEndpointKey,
  getConnectionPieceId,
  getLineblockPremainLinksFromLayout,
  getPieceCells,
  getPrivolavaciaConnectionKey,
  getRenderablePieces,
  isLineblockPieceType,
  isPrivolavaciaCounterPieceType,
  isPrivolavaciaSignalPieceType,
  isPremainSignalPieceType,
  isSwitchButtonPieceType,
  isSwitchPieceType,
  parseCellRef,
  toCellKey,
} from '@/lib/station/layout';
export type { LayoutExpansionDirection } from '@/lib/station/layout';
