export type {
  ComponentGroups,
  GroupSelection,
  GroupState,
  PieceOrientation,
  Space,
  StateGroup,
  StateGroupRegistry,
  StateVariant,
  TextConfig,
  TileCatalog,
  TileData,
  TraversableRouteMap,
  TraversableStateKey,
  TraversableStateMap,
} from '@/lib/station/tile-types';
